### ISSUE TITLE
Fall 2018 Wishlist

### ISSUE THREAD

**Issue by milancurcic** [milancurcic/lunch-bytes#7]
Topics requested by the attendees:

* Python for complete beginners
* Python + Dask for parallel data analysis
* Getting started with cloud computing (AWS or DigitalOcean)

**Comment by tibbben** [comment]
I can do python for absolute beginners (as the software carpentry style introduction) and help with python parallel using dask and concurrent futures ...

**Comment by raybellwaves** [comment]
@tibbben thanks. I did basic python today. If you could do dask that would be awesome! I think there is plenty of material in https://github.com/dask/dask-tutorial and https://github.com/dask/dask-examples which should be good to go out of the box. I didn't have time to do dask-jobqueue today so you are also welcome to present that (https://github.com/milancurcic/lunch-bytes/blob/master/Fall_2018/LB14/py_intro_lb_nb_parallel.ipynb)

**Comment by raybellwaves** [comment]
Very excited for the cloud computing one

**Comment by milancurcic** [comment]
@tibben That would be fantastic. @raybellwaves did good job today with getting started with Python on Pegasus, but I think the bar was pretty high and mostly an overview. I think we'd still need a dedicated seminar with focus on programming and the language itself.

I like the idea of @tibben doing Python for absolute beginners, and @raybellwaves and @tibben teaming up on Dask.

Now that there seems to be demand for cloud computing, I will be happy to do that one, though later in the semester. Earlier, I will probably do one on git + Github, and perhaps one on Markdown.

A strong recommendation when designing a seminar: If you want to teach a topic and people to follow, please stick to **one** topic! If you want to do an overview of 5 topics, that's OK, but don't try to teach them in detail and expect people to follow.

**Comment by milancurcic** [comment]
There was also a question and interest in a Python-specific course. I mentioned Software Carpentry, but I think that happens twice a year. Perhaps we can start talking about designing a mini-course as part of Lunch Bytes, with something like:

* Python
* numpy
* matplotlib
* notebooks
* pandas, xarray, dask, and similar

**Comment by raybellwaves** [comment]
> I think we'd still need a dedicated seminar with focus on programming and the language itself.

@milancurcic definitely. Less is more. I had too much in my talk today so should have decided between show and tell (with little live coding and don't have the audience following along) or something you can teach with the audience in 45 minutes.

**Comment by milancurcic** [comment]
We got a request for a LaTeX seminar.

**Comment by raybellwaves** [comment]
Bash/shell scripting? Awk, sed, find, grep. Maybe covering CDO and NCO as well?
Software carpentry have a nice lesson on this
http://swcarpentry.github.io/shell-novice/

**Comment by raybellwaves** [comment]
Some git material here: https://github.com/AllenDowney/amgit

**Comment by raybellwaves** [comment]
Probably on the periphery but testing/continuous integration/developing software. e.g. pytest, flake8, Travis CI, conda forge.

**Comment by milancurcic** [comment]
@raybellwaves Are these topics you'd like to learn or a suggestion for a seminar to teach? On their own they seem very specific and perhaps advanced.

Scientific DevOps (I saw some people call it SciDevOps) is something I haven't seen a seminar about and I think most people are not aware is a thing. Maybe a good topic for an overview, with examples in Github or GitLab.

**Comment by milancurcic** [comment]
> Bash/shell scripting? Awk, sed, find, grep. Maybe covering CDO and NCO as well?

These are good and important topics. I wonder how much people use stuff like bash+awk+sed nowadays. Myself, as soon as I have to write a loop or if-block in shell I switch to Python. It may be redundant.

I would really like to hear a seminar on NCO. Not much material out there.

Dian did a seminar on CDO: https://github.com/milancurcic/lunch-bytes/tree/master/Fall_2015/LB02

If you can find a good speaker, I'm all for doing seminars on some topics that we already had in the past. We are now catering to a new generation of students anyway.

**Comment by raybellwaves** [comment]
> @raybellwaves Are these topics you'd like to learn or a suggestion for a seminar to teach? On their own they seem very specific and perhaps advanced.

I would like to learn. I have experience with python software development but it's all self taught along the way. SciDevOps would be useful. It could take a while to setup but you could have an exercise where people work out how to contribute code to the same repo and work on different parts (I will see if some kind of lesson exists like this; may overlap with the git lesson).

> I wonder how much people use stuff like bash+awk+sed nowadays.

Very true. xarray and other packages in https://github.com/pydata/xarray/blob/master/doc/related-projects.rst have the capability of CDO and NCO. Whilst the performance may not quite be quite as good, the python implementation is more user friendly.

**Comment by tibbben** [comment]
> Bash/shell scripting? Awk, sed, find, grep. Maybe covering CDO and NCO as well?

> These are good and important topics. I wonder how much people use stuff like bash+awk+sed nowadays. Myself, as soon as I have to write a loop or if-block in shell I switch to Python. It may be redundant.

perhaps still useful when on remote machines ...

As a total aside, perhaps we should have a virtual meeting sometime just to coordinate a little bit? Especially if I am to help out with some of these.

**Comment by milancurcic** [comment]
I'll set up a Doodle thing..

**Comment by milancurcic** [comment]
We got another request for a seminar on xarray.

I'm starting to think if we should design a survey. A topic for our meeting tomorrow.

**Comment by tibbben** [comment]
Possible seminars:
Paul Clough (library) - virtual environments

**Comment by tibbben** [comment]
Abraham Parrish - GIS library
Cameron Riopelle - Stats and data Library

**Comment by raybellwaves** [comment]
some good stuff here https://carpentrieslab.github.io/python-aos-lesson/
