### ISSUE TITLE
Add teaching guidelines to README.md

### ISSUE THREAD

**Issue by raybellwaves** [milancurcic/lunch-bytes#9]
This came from my comment https://github.com/milancurcic/lunch-bytes/issues/7#issuecomment-415859273

Things worth mentioning:

- 45 mins
- Show and tell vs. live coding with teaching
- Welcome to ask @milancurcic or me for feedback before and/or after seminar.
- anything else?

**Comment by milancurcic** [comment]
Great idea! Can you draft the initial presenter guidelines and I will chime in? One bullet that comes to mind right now:

* Any format welcome! Slides, live-code, whiteboard, or just talk.

**Comment by milancurcic** [comment]
* Up to 45 minutes (can be shorter)
